# MSTICPy ex-PyPI Production pipeline

trigger: none
pr: none

# This pipeline is used to publish the MSTICPy package to PyPI
name: 1ES-MSTICPy-No-Longer-Publish-$(date:yyyyMMdd)$(rev:.r)

parameters:
  - name: Artifact
    type: string
    default: dist
    displayName: Directory to store the built artifacts
  - name: Feed
    type: string
    default: testpypi
    displayName: The feed to not publish to
    values:
      - testpypi
      - pypi

resources:
  repositories:
  - repository: msticpy
    name: microsoft/msticpy
    type: github
    ref: main
    endpoint: Microsoft
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: MSSecurity-1ES-Build-Agents-Pool
      image: MSSecurity-1ES-Windows-2022
      os: windows
    stages:
    - stage: publishTasks
      displayName: PublishTasks
      dependsOn: SDLSources

      jobs:
      - job: publishJob
        displayName: PublishJob
        variables:
          - name: DistDir
            value: $(Pipeline.Workspace)\${{ parameters.Artifact }}
        steps:
        - powershell: |
            echo This pipeline no longer does anything useful
            exit 0